### ISSUE TITLE
Abort trap: 6

### ISSUE THREAD

**Issue by leonsp** [CoolerVoid/Mosca#2]
I'm getting `Abort trap: 6` on both Ruby and Javascript projects.

I installed Mosca:

    $ brew install pcre
    ==> Downloading https://homebrew.bintray.com/bottles/pcre-8.38.el_capitan.bottle.tar.gz
    ######################################################################## 100.0%
    ==> Pouring pcre-8.38.el_capitan.bottle.tar.gz

    $ git clone git@github.com:CoolerVoid/Mosca.git

    $ cd Mosca/

    $ make
    gcc -W -Wall -Wextra  -Ofast -fstack-protector-all  -c *.c
    file_ops.c:194:10: warning: comparison of array 'log_file' not equal to a null pointer is always true [-Wtautological-pointer-compare]
                                                    if(log_file != NULL)
                                                       ^~~~~~~~    ~~~~
    1 warning generated.
    gcc -o mosca *.o -Wl -lpcre

When I try to run it against a Ruby or Javascript project, it dies with `Abort trap: 6`

    $ ./mosca --egg eggs/ruby_common_fail.egg --path ../my_rails_project --ext "\\.rb$" --log my_rails_project.txt
    Egg: eggs/ruby_common_fail.egg
    Path: ../my_rails_project
    Extension: \.rb$
    Log file: my_rails_project.txt  

    =====================================
     Path: ../my_rails_project/app/controllers/activities_controller.rb
     Use Module: eggs/ruby_common_fail.egg
    Abort trap: 6

**Comment by CoolerVoid** [comment]
So i test at Linux in "gcc version 5.1.1 " run here without error, without warning...
please change your Makefile compile -Ofast to -O2.

At your --path you need use fullpath example:
path_app/
/user/dude/rubyproject

Try again 

cheers
