### ISSUE TITLE
Issue with a PHP project

### ISSUE THREAD

**Issue by JohnnyAMD** [CoolerVoid/Mosca#3]
Hi mate, 

I'm having Mosca compiled under a Kali 2.0 Sana. 

Also I do have an OOP PHP code project. 

Each time when I'm running mosca I'm getting the following error: 

CLI: ./mosca --egg egg/php_fails.egg --path /root/Desktop/project/mysite/code/ --ext "\\.php$" --log reports.txt

Error: 
"
Tue Jan 12 11:57:22 2016 file_ops.c[42] ReadLines():  error in to open() file
"
Is there any particular switch which I can use to debug this further and see what might be the problem before bothering you? :)

Thanks!

**Comment by CoolerVoid** [comment]
Hello sir, 
Take this following example to try again please:
./mosca --egg eggs/php_common_fail.egg --path /var/www/html/php_project/ --ext "\\.php$" --log report1

If not run...
at this line https://github.com/CoolerVoid/Mosca/blob/master/file_ops.c#L42
change DEBUG to perror and load lib "errno.h" at head of file, and compile and try run again to view the information of error... i guess can be a permission mistake or another problem at file...

cheers!

**Comment by JohnnyAMD** [comment]
Hi, 

Thanks for your quick response. I confirm that is working as you advertised. 

However, will do the debug trick and see why using that initial egg gave me error.

Cheers!

**Comment by CoolerVoid** [comment]
Ok you are welcome, 
so i update the source now... i add XML at output too... i fix all possible bugs
Try again pls

Cheers!

**Comment by JohnnyAMD** [comment]
Okay. So I did that debugging thing. The result it was pretty simple. There is nothing wrong with your code but with my ability to check the egg folder and be able to see that there are just couple of eggs defined. No php_fail.egg file though :)

Thanks and I have to apologises for my stupidity. 

The xml output is quite useful, although I'm okay with the txt one at the moment. 

You can close this issue now.
